name: bed_classify
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Remove if you want CPU-only
  - pillow
  - pip
  - pip:
      - git+https://github.com/openai/CLIP.git
